home_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }


extranet_home:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /ydrive
    requirements:
        _locale: en|fr


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

